<?php

use Fisharebest\Webtrees\Gedcom;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;

$thePlace = strstr($placeName, Gedcom::PLACE_SEPARATOR, true);
if (!$thePlace) {
  $thePlace = $placeName;
}
?>
    
<div class="form-group">
    <?php if ($withLabel): ?>
      <label class="col-form-label" for="<?= $id ?>">
          <?= I18N::translate('GOV id') ?>
      </label>
    <?php endif ?>
    <?php 
      //we'd like to use far fa-compass but we'd have to import explicitly
    ?>
    
    <div><span class="wt-icon-map-gov"><i class="fas fa-play fa-fw" aria-hidden="true"></i></span> <a href="http://gov.genealogy.net/search/<?= $thePlace === ''?'extended':'name/?name='.$thePlace ?>" target="_blank"><?= I18N::translate('Look up a matching GOV id on the GOV server') ?></a></div>
    
    <?php if ($internal): ?>
      <div><?= I18N::translate('Note: The mapping from place to GOV id is stored outside the gedcom data.') ?></div>
      <div><?= ($govId === null)?'':I18N::translate('Save the current id in order to reload the place hierarchy data from the GOV server.') ?></div>
      <div><?= ($govId === null)?'':I18N::translate('You may also save an empty id in order to remove the mapping.') ?></div>
    <?php endif ?>

</div>

<?php
  //data-minimum-input-length: usually 12, but there are some shorter ones, such as adm_368372
?>

<select
    autocomplete="off"
    class="form-control select2gov"
    data-ajax--delay="350"
    data-minimum-input-length="10"
    data-ajax--type="POST"
    data-ajax--url="<?= e(route('module', [
        'module' => $moduleName,
        'action' => 'Select2GovId',
    ])) ?>"
    data-allow-clear="true"
    data-placeholder=""
    id="<?= $id ?>"
    name="<?= $name ?>"
    <?= (($govId === null) && $internal)?'required':'' ?>>
    <?php if ($govId !== null): ?>
        <option value="<?= $govId ?>">
            <?= $govId ?>
        </option>
    <?php else: ?>
        <option></option>
    <?php endif ?>
</select>

<?php View::push('javascript') ?>
<?php if ($modal): /* cf ajax.phtml (in case this is used as a modal), with adjustment for 'noResults' */ ?>
<script>
//don't do the following on DOMContentLoaded - we're executing after this element has already been rendered 
//document.addEventListener("DOMContentLoaded", function () {
  $("#wt-ajax-modal")
    .on("shown.bs.modal", function (event) {
      // Activate autocomplete fields
      $(".select2gov", $(this)).select2({
        dropdownParent: $(this),
        language: {
          "noResults": function(){
              return "<?= I18N::translate('Invalid GOV id! Valid GOV ids are e.g. \'EITTZE_W3091\', \'object_1086218\'.') ?>";
          }
        },
        escapeMarkup: function (x) { return x; }
      });
    });
//});
</script>
<?php else: /* cf webtrees.js, with adjustment for 'noResults' */ ?>
<script>
$(function() {
  $("select.select2gov").select2({
        language: {
            "noResults": function(){
                return "<?= I18N::translate('Invalid GOV id! Valid GOV ids are e.g. \'EITTZE_W3091\', \'object_1086218\'.') ?>";
            }
        },
        // Do not escape - we do it on the server.
        escapeMarkup: function (x) {
            return x;
        }
    });
  
  //do we really need this?
  $("select.select2gov:not([multiple])")
    .on("select2:unselect", function (evt) {
        $(evt.delegateTarget).html("<option value=\"\" selected></option>");
    });
 
});
</script>
<?php endif ?>

<?php View::endpush() ?>