<?php

use Fisharebest\Webtrees\Gedcom;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;

$thePlace = strstr($placeName, Gedcom::PLACE_SEPARATOR, true);
if (!$thePlace) {
  $thePlace = $placeName;
}
?>
    
<div class="form-group">
    <?php if ($withLabel): ?>
      <label class="col-form-label" for="<?= $id ?>">
          <?= I18N::translate('GOV id') ?>
      </label>
    <?php endif ?>
    
    <div><i class="fas fa-compass fa-fw wt-icon-map-gov" aria-hidden="true">  </i> <a href="http://gov.genealogy.net/search/<?= $thePlace === ''?'extended':'name/?name='.$thePlace ?>" target="_blank"><?= I18N::translate('Look up a matching GOV id on the GOV server') ?></a></div>
    
    <?php if ($internal): ?>
      <div><?= I18N::translate('Note: The mapping from place to GOV id is stored outside the gedcom data.') ?></div>
      <div><?= ($govId === null)?'':I18N::translate('Save the current id in order to reload the place hierarchy data from the GOV server.') ?></div>
      <div><?= ($govId === null)?'':I18N::translate('You may also save an empty id in order to remove the mapping.') ?></div>
    <?php endif ?>

</div>


<select
    autocomplete="off"
    class="form-control select2gov"
    data-ajax--delay="350"
    data-minimum-input-length="12"
    data-ajax--type="POST"
    data-ajax--url="<?= e(route('module', [
        'module' => $moduleName,
        'action' => 'Select2GovId',
    ])) ?>"
    data-allow-clear="true"
    data-placeholder=""
    id="<?= $id ?>"
    name="<?= $name ?>"
    <?= ($govId === null)?'required':'' ?>>
    <?php if ($govId !== null): ?>
        <option value="<?= $govId ?>">
            <?= $govId ?>
        </option>
    <?php else: ?>
        <option></option>
    <?php endif ?>
</select>

<?php View::push('javascript') ?>
<?php /* cf webtrees.min.js, with adjustment for 'noResults' */ ?>
<script>
$(document).ready(function() {
  console.log("select2");
  $("select.select2gov").select2({
        language: {
       "noResults": function(){
           return "<?= I18N::translate('Invalid Id! Valid GOV ids are e.g. \'EITTZE_W3091\', \'object_1086218\'.') ?>";
       }
   },
        // Do not escape - we do it on the server.
        escapeMarkup: function (x) {
            return x;
        },
    });
    
  $("select.select2gov:not([multiple])")
    .on("select2:unselect", function (evt) {
        $(evt.delegateTarget).html("<option value=\"\" selected></option>");
    });  
});
</script>
<?php View::endpush() ?>