<button 
    class="btn btn-link btn-sm" 
    type="button" 
    data-toggle="modal" 
    data-target="#wt-ajax-modal" 
    data-href="<?=
    e(route('module', [
        'module' => $moduleName,
        'action' => 'EditGovMapping',
        'place-name' => $fact->place()->gedcomName(),
        'ged' => $fact->record()->tree()->name()
    ]));
    ?>" 
    data-select-id="<?= 'UNUSED' ?>" 
    title="<?= $title ?>">
        <?= view($moduleName . '::icons/map-gov') ?>
        <span class="sr-only"><?= $title ?></span>
</button>

